import 'dart:ui';

import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:google_fonts/google_fonts.dart';

final lightTheme = FlexThemeData.light(
  colors: const FlexSchemeColor(
    primary: Color(0xFFE040FB),
    primaryVariant: Color(0xFF3700B3),
    secondary: Color(0xFF03DAC6),
    secondaryVariant: Color(0xFF018786),
    appBarColor: Color(0xFF018786),
    error: Color(0xFFB00020),
  ),
  surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
  blendLevel: 16,
  appBarStyle: FlexAppBarStyle.primary,
  appBarOpacity: 0.94,
  appBarElevation: 8,
  transparentStatusBar: true,
  tabBarStyle: FlexTabBarStyle.forAppBar,
  tooltipsMatchBackground: false,
  swapColors: false,
  lightIsWhite: false,
  useSubThemes: true,
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
// fontFamily: GoogleFonts.notoSans().fontFamily,
  subThemesData: const FlexSubThemesData(
    useTextTheme: true,
    defaultRadius: 0,
    fabUseShape: true,
    interactionEffects: true,
    bottomNavigationBarOpacity: 0.95,
    bottomNavigationBarElevation: 0,
    inputDecoratorIsFilled: true,
    inputDecoratorBorderType: FlexInputBorderType.outline,
    inputDecoratorUnfocusedHasBorder: false,
    blendOnColors: true,
    blendTextTheme: true,
    popupMenuOpacity: 0.95,
  ),
);
final darkTheme = FlexThemeData.dark(
  colors: const FlexSchemeColor(
    primary: Color(0xFFF43F5E),
    primaryVariant: Color(0xFF5B21B6),
    secondary: Color(0xFF03DAC6),
    secondaryVariant: Color(0xFF03DAC6),
    appBarColor: Color(0xFF03DAC6),
    error: Color(0xFFCF6679),
  ),
  surfaceMode: FlexSurfaceMode.level,
  blendLevel: 16,
  appBarStyle: FlexAppBarStyle.material,
  appBarOpacity: 0.7,
  appBarElevation: 8,
  transparentStatusBar: true,
  tabBarStyle: FlexTabBarStyle.forAppBar,
  tooltipsMatchBackground: false,
  swapColors: false,
  darkIsTrueBlack: false,
  useSubThemes: true,
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  fontFamily: GoogleFonts.archivo().fontFamily,
  subThemesData: const FlexSubThemesData(
    useTextTheme: true,
    defaultRadius: 4,
    fabUseShape: true,
    interactionEffects: true,
    bottomNavigationBarOpacity: 0.9,
    bottomNavigationBarElevation: 0,
    inputDecoratorIsFilled: true,
    inputDecoratorBorderType: FlexInputBorderType.outline,
    inputDecoratorUnfocusedHasBorder: false,
    blendOnColors: true,
    blendTextTheme: false,
    popupMenuOpacity: 0.95,
  ),
);
